name: goscele
description: GoScele is mobile version of Scele Fasilkom UI.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  table_calendar: ^2.3.3 # Calendar widget for schedules
  dio: ^3.0.10 # HTTP request package
  get_it: ^5.0.3 # Service locator package
  hive: ^1.4.4+1 # Local storage package
  hive_flutter: ^0.3.1 # Extension for Hive to work on Flutter
  dartz: ^0.9.2 # Functional programming package
  connectivity: ^2.0.2 # Internet connection checker package

  # State management packages
  stacked: ^1.7.7 # Package to implement MVVM pattern using Provider
  stacked_services: ^0.6.0+1 # Extension for Stacked that contains extra services
  stacked_hooks: ^0.1.3+2 # Extension for Stacked to use hooks
  flutter_hooks: ^0.15.0 # Flutter implementation of react hooks

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2 # Extension for Hive to generate class adapters
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - images/ic_launcher.png
